config/routes.rb
Rails.application.routes.draw do

  root :to =>'static_pages#home'

  #1.DEVISE ROUTES
  #1.1 Session User
  devise_scope :session_user do
    get 'iniciar_sesion', to: 'devise/sessions#new'
    get 'registro', to: 'session_users/registrations#nuevo_registro'
    get 'cambio_contrasena_u',
        to: 'session_users/sessions#edit_password',
        as: 'cambio_contrasena_session_user'
    get 'recuperar_contrasena', to: 'session_users/passwords#new'
    patch 'actualizar_contrasena', to: 'session_users/sessions#update_password'
    post 'reestablecer_password',
         to:'session_users/passwords#permit_reset_password'
    delete 'cerrar_sesion', to: 'devise/sessions#destroy'
  end

  devise_for :session_users ,  :controllers =>
                                { :registrations => 'session_users/registrations',
                                  :sessions =>'session_users/sessions',
                                  :passwords => 'session_users/passwords'}
  #1.2. Funcionarios
  scope module: 'funcionarios' do
    post 'funcionarios/get_info',
         to: 'funcionarios#get_info'
    resources :funcionarios, only: [:create, :update]


    #1.2.1 Verificar Solicitudes de Preinscripcion

    # 1.2.1.1 busqueda de preinscripcion a verificar
    resources :verificar_preinscripcions, only: [:index, :new, :create]
    post 'verificar_preinscripcion/buscar_solicitud',
         to: 'verificar_preinscripcions#wf_buscar_solicitud'

    # 1.2.1.2 Wizard verificar Preincripcion
    get 'verificar_preinscripcion_escuela/informacion/:id',
        to: 'verificar_preinscripcions#wf_verificar_informacion_general',
        as: :verificar_informacion_general

    get 'verificar_preinscripcion_escuela/planos_infraestructura/:id',
        to: 'verificar_preinscripcions#wf_verificar_planos',
        as: :verificar_planos

    get 'verificar_preinscripcion_escuela/rcv/:id',
        to: 'verificar_preinscripcions#wf_verificar_rcv_flota',
        as: :verificar_rcv


    get 'verificar_preinscripcion_escuela/vehiculos/:id',
        to: 'verificar_preinscripcions#wf_verificar_vehiculos',
        as: :verificar_vehiculos

    get 'verificar_preinscripcion_escuela/circuitos_manejo/:id',
        to: 'verificar_preinscripcions#wf_verificar_circuitos_manejo',
        as: :verificar_circuitos

    get 'verificar_preinscripcion_escuela/trabajadores/:id',
        to: 'verificar_preinscripcions#wf_verificar_trabajadores',
        as: :verificar_trabajadores
    
    #1.2.1.3 Acciones sobre Verificaciones de Solicitud Adecuacion y construccion
    get 'diferir_preinscripcion_escuela/:id',
        to: 'verificar_preinscripcions#wf_diferir_solicitud',
        as: :diferir_preinscripcion_escuela

    get 'inspeccionar_escuela/:id',
        to: 'verificar_preinscripcions#wf_realizar_inspeccion',
        as: :inspeccionar_preinscripcion_escuela

    get 'estudiar_preinscripcion_escuela/:id',
        to: 'verificar_preinscripcions#wf_realizar_estudio',
        as: :estudiar_preinscripcion_escuela

    get 'cancelar_preinscripcion_escuela/:id',
        to: 'verificar_preinscripcions#wf_cancelar_inspeccion',
        as: :cancelar_preinscripcion_escuela

    get 'solicitud_procesada/:id',
        to: 'verificar_preinscripcions#wf_solitud_procesada',
        as: :verificada

    # post 'rechazar_preinscripcion_escuela/:id',
    #     to: 'verificar_preinscripcions#wf_rechazar_solicitud',
    #     as: :rechazar_preinscripcion_escuela

    # get 'aprobar_preinscripcion_escuela/:id',
    #     to: 'verificar_preinscripcions#wf_aprobar_solicitud',
    #     as: :aprobar_preinscripcion_escuela

  end

  # 1.2.1 Registro
  devise_scope :funcionario do

    get 'funcionarios/new',
        to: 'funcionarios/registrations#new_funcionario'
    get 'funcionarios/show/:id',
        to: 'funcionarios/registrations#show', as: 'funcionarios_show_funcionario'
    post 'funcionarios/create_funcionario',
         to: 'funcionarios/registrations#create_funcionario'
    get 'funcionarios/editf',
        to: 'funcionarios/registrations#edit_funcionario'
    post 'funcionarios/buscar_funcionarios',
         to: 'funcionarios/registrations#buscar_funcionarios'
    get 'funcionarios/editar/:id',
        to: 'funcionarios/registrations#edit_rols_funcionario', as: 'funcionarios_editar_funcionario'
    post 'funcionarios/update_funcionario/:id',
         to: 'funcionarios/registrations#update_funcionario', as: 'funcionarios/update_funcionario'
  end

  devise_for :funcionarios, controllers: { sessions: 'funcionarios/sessions',
                                           registrations: 'funcionarios/registrations'}

  #2. Roles
  resources :rols

  #3. Registro de Interesados
  scope module: 'interesado_cets' do
    resources :interesado_cets, only: [:new, :index, :create, :update, :show]
    post 'interesado_cets/find_interesado_ajax',
         to: 'interesado_cets#find_interesado_ajax'
    resources :tipo_escuelas
  end

  #4. Dynamic Selects
  namespace :dynamic_select do
    get ':estado_id/ciudades', to: 'ciudades#index', as: 'ciudades'
    get ':estado_id/municipios', to: 'municipios#index', as: 'municipios'
    get ':municipio_id/parroquias', to: 'parroquias#index', as: 'parroquias'
    post 'ciudad_municipio', to: 'ciudades#ciudad_municipio'
  end

  #5. Nested Resources Acceder a operadoras de un Representante legal
  resources :representante_legal do
    resources :escuela_transportes, controller: 'escuela_transportes/escuela_transportes'
  end

  resources :jquery_file_uploads, only: [:create, :destroy, :index] do
    member do
      delete 'destroy_no_paginado'
    end
  end

  #6. Preinscripcion de Escuela de Transporte
  namespace :escuela_transportes do

    #6.1 Editar el RIF en caso de que este vencido
    resources :update_rif, only: [:edit, :update]

    #6.2 Documentos del Registro Inicial
    get 'cargar_documentos_registro/:id', to:'documentos_registros#new',as: :cargar_documentos_registro
    post 'documentos_registro/:id', to:'documentos_registros#create',as: :documentos_registro

    #6.3 WIZARD
    #6.3.1 Informacion General e Inicio
    resources :informacion_general, only: [:index, :create, :update, :edit]
    post 'informacion_general/new', to: 'informacion_general#new', as: 'informacion_general_new'
    get 'informacion_general/new', to: 'informacion_general#new_get', as: 'informacion_general_new_get'

    #6.3.2 Documentos Planos de Infraestructura
    get  'cargar_planos_infraestructura/:id', to:'planos_infraestructura#new',
         as: :cargar_planos
    post 'guardar_planos_infraestructura/:id', to:'planos_infraestructura#create',
         as: :guardar_planos

    #6.3.3 Seguro RCV
    resources :seguros, only: [:new, :create]
    patch '/seguros/', to: 'seguros#create'
    post '/rif/', to: 'seguros#rif_aseguradora', as: :rif_a

    #6.3.4 Documentos de Vehiculos
    resources :vehiculos
    post 'vehiculos/buscar_vehiculo_pre', to: 'vehiculos#buscar_vehiculo_pre'
    delete '/eliminar_circuito/:id',
           to: 'circuitos_manejo#eliminar_circuito',
           as: :eliminar_circuito

    #6.3.5 Circuitos de manejo
    get  'listar_circuitos_manejo/:id', to: 'circuitos_manejo#index_circuitos',
         as: :index_circuitos
    get  'ver_circuito_manejo/:id', to: 'circuitos_manejo#show',
         as: :ver_circuito
    get  'crear_circuito_manejo/:id', to:'circuitos_manejo#new',
         as: :crear_circuito
    get  'aditar_circuito_manejo/:id', to:'circuitos_manejo#editar_circuito',
         as: :editar_circuito
    get 'guardar_documentos_circuito_manejo/:id', to:'circuitos_manejo#guardar_documentos_circuito',
        as: :guardar_documentos_circuito
    post 'guardar_circuito_manejo/:id', to:'circuitos_manejo#guardar_circuito',
         as: :guardar_circuito
    patch 'actualizar_circuito_manejo/:id', to:'circuitos_manejo#actualizar_circuito',
          as: :actualizar_circuito

    #6.3.6 Trabajadores
    get 'listar_personal/:id',to: 'personals#index', as: :listar_personals ,constraints: {id: /\d+/}
    get 'find/:id', to:'personals#find',as: :encontrar_personal
    get 'instructor_documents/', to: 'personals#instructor_documents'
    get 'editar_trabajador/:id', to: 'personals#edit', as: :editar_personal
    get 'ver_trabajador/:id', to: 'personals#show', as: :ver_personal
    patch 'update/:id', to: 'personals#update', as: :actualizar_personal
    post 'found/:id', to: 'personals#found', as: :encontro_personal
    post 'save/:id', to: 'personals#save', as: :guardar_personal
    delete 'remove/:id', to: 'personals#remove', as: :eliminar_personal


    #6.3.7 Planilla de Solicitud
    get 'solicitud/preparar/:id',to:'solicitud_adecuacion_acciones#preparar_solicitud', as: :preparar_solicitud_adecuacion
    get 'solicitud/modificar/:id',to:'solicitud_adecuacion_acciones#modificar_solicitud', as: :modificar_solicitud_adecuacion
    get 'solicitud/print', to: 'solicitud_adecuacion_acciones#print', as: :print_solicitud_adecuacion
    get 'solicitud/ver', to: 'solicitud_adecuacion_acciones#ver', as: :ver_solicitud_adecuacion

  end
end

# == Route Map
#
#                                            Prefix Verb   URI Pattern                                                                         Controller#Action
#               escuela_transportes_personals_index GET    /escuela_transportes/personals/index(.:format)                                      escuela_transportes/personals#index
#                escuela_transportes_personals_edit GET    /escuela_transportes/personals/edit(.:format)                                       escuela_transportes/personals#edit
#                escuela_transportes_personals_find GET    /escuela_transportes/personals/find(.:format)                                       escuela_transportes/personals#find
#               escuela_transportes_personals_found GET    /escuela_transportes/personals/found(.:format)                                      escuela_transportes/personals#found

app/controllers/static_pages_controller.rb
# -*- encoding : utf-8 -*-
class StaticPagesController < ApplicationController
  helper_method :resource, :resource_name, :devise_mapping
  def home
  end

  def resource_name
    :session_user
  end

  def resource
    @resource ||= SessionUser.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:session_user]
  end
  protected
    def self.funcion_sistema
      return "StaticPage"
    end
end

app/views/static_pages/_form.html.haml
.panel.panel-default
  .panel-body
    %h4 Usuarios Registrados
    = form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "form form-signup", role: "form"}) do |f|
      .form-group
        .input-group
          .input-group-addon.input_gris
            %i.fa.fa-user.icon-color
          = f.text_field :email, :class=>"form-control", :placeholder=>"Email", :required =>'required', autofocus: true
      .form-group
        .input-group
          .input-group-addon.input_gris
            %i.fa.fa-lock.icon-color
          = f.password_field :password, :class=>"form-control", :placeholder=>"Contraseña", :required =>'required', autocomplete: "off"
      .form-group
        - if devise_mapping.rememberable?
          = f.check_box :remember_me
          = f.label :remember_me, 'Mantener Conectado'

      .row
        .col-md-6
          = f.submit "Entrar", class: 'btn btn-success btn-block'
        .col-md-6
          - if devise_mapping.registerable? && controller_name != 'registrations'
            = link_to "Registrarse!", registro_path,  "data-no-turbolink" => true
      .row
        .col-md-12
          = link_to "Funcionarios", new_funcionario_session_path
      .row
        .col-md-12
          %br/
          - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
            = link_to "¿Olvido su contraseña?", recuperar_contrasena_path
      .row
        .col-md-12
          - if devise_mapping.confirmable? && controller_name != 'confirmations'
            = link_to "¿No recibió el correo de confirmación?", new_confirmation_path(resource_name)
            %br/

app/views/static_pages/_funcionario_logued.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Inicio
    %ol.breadcrumb
      %li.text-navy
        %b
          Inicio
      %li
.row
  .col-lg-12
    .wrapper.wrapper-content.animated.fadeInUp
      .ibox
        .ibox-content.text-center
          .row
            .col-lg-12.text-center
              %h2
                Funcionarios
              %br/
              = image_tag 'bienvenidos_usuarios.png'

app/views/static_pages/_logued.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Inicio
.row
  .col-lg-12
    .wrapper.wrapper-content.animated.fadeInUp
      .ibox
        .ibox-content.text-center
          .row
            .col-lg-12
              = image_tag 'bienvenidos_usuarios.png'

app/views/static_pages/_not_logued.html.haml
.row.border-bottom.white-bg.dashboard-header
  .col-lg-10.col-lg-offset-1
    .row
      .col-md-8
        #myCarousel.carousel.slide
          / Indicators
          %ol.carousel-indicators
            %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
            %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
            %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
          / Wrapper for slides
          .carousel-inner
            #slide1.item.active
              .carousel-caption
            / end carousel-caption
            / end item
            #slide2.item
              .carousel-caption
            / end carousel-caption
            / end item
            #slide3.item
              .carousel-caption
          / end carousel-caption
          / end item
          / carousel-inner
          / Controls
          %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
            %span.icon-prev
          %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
            %span.icon-next
      / end myCarousel
      / end col-md-8
      / login
      .col-md-4
        = render 'form'
.row.graylight-bg
  .col-lg-12
    .wrapper
      .row
        .col-lg-10.col-lg-offset-1

          .row
            .col-lg-4
              .well.well-lg.c4
                .row
                  .col-sm-4
                    = link_to root_url, class: 'link_index' do
                      = image_tag 'transporte.png', class: 'btn_img'
                  .col-md-8
                    %br/
                    = link_to 'Requisitos', root_url, class: 'link_index'
            / end well c4
            .col-lg-4
              .well.well-lg.c5
                .row
                  .col-sm-4
                    = link_to root_url, class: 'link_index' do
                      = image_tag 'servicios.png', class: 'btn_img'
                  .col-md-8
                    %br/
                    = link_to 'Servicios', root_url, class: 'link_index'
            / end well c5
            .col-lg-4
              .well.well-lg.c6
                .row
                  .col-sm-4
                    = link_to root_url, class: 'link_index' do
                      = image_tag 'noticias.png', class: 'btn_img'
                  .col-md-8
                    %br/
                    = link_to 'Noticias', root_url, class: 'link_index'

app/views/static_pages/home.html.haml
- if session_user_signed_in?
  = render partial: 'logued'
- elsif funcionario_signed_in?
  = render partial: 'funcionario_logued'
- else
  = render partial: 'not_logued'