config/routes.rb
Rails.application.routes.draw do

  root :to =>'static_pages#home'

  #1.DEVISE ROUTES
  #1.1 Session User
  devise_scope :session_user do
    get 'iniciar_sesion', to: 'devise/sessions#new'
    get 'registro', to: 'session_users/registrations#nuevo_registro'
    get 'cambio_contrasena_u',
        to: 'session_users/sessions#edit_password',
        as: 'cambio_contrasena_session_user'
    get 'recuperar_contrasena', to: 'session_users/passwords#new'
    patch 'actualizar_contrasena', to: 'session_users/sessions#update_password'
    post 'reestablecer_password',
         to:'session_users/passwords#permit_reset_password'
    delete 'cerrar_sesion', to: 'devise/sessions#destroy'
  end

  devise_for :session_users ,  :controllers =>
                                { :registrations => 'session_users/registrations',
                                  :sessions =>'session_users/sessions',
                                  :passwords => 'session_users/passwords'}
  #1.2. Funcionarios
  scope module: 'funcionarios' do
    post 'funcionarios/get_info',
         to: 'funcionarios#get_info'
    resources :funcionarios, only: [:create, :update]


    #1.2.1 Verificar Solicitudes de Preinscripcion

    # 1.2.1.1 busqueda de preinscripcion a verificar
    resources :verificar_preinscripcions, only: [:index, :new, :create]
    post 'verificar_preinscripcion/buscar_solicitud',
         to: 'verificar_preinscripcions#wf_buscar_solicitud'

    # 1.2.1.2 Wizard verificar Preincripcion
    get 'verificar_preinscripcion_escuela/informacion/:id',
        to: 'verificar_preinscripcions#wf_verificar_informacion_general',
        as: :verificar_informacion_general

    get 'verificar_preinscripcion_escuela/planos_infraestructura/:id',
        to: 'verificar_preinscripcions#wf_verificar_planos',
        as: :verificar_planos

    get 'verificar_preinscripcion_escuela/rcv/:id',
        to: 'verificar_preinscripcions#wf_verificar_rcv_flota',
        as: :verificar_rcv


    get 'verificar_preinscripcion_escuela/vehiculos/:id',
        to: 'verificar_preinscripcions#wf_verificar_vehiculos',
        as: :verificar_vehiculos

    get 'verificar_preinscripcion_escuela/circuitos_manejo/:id',
        to: 'verificar_preinscripcions#wf_verificar_circuitos_manejo',
        as: :verificar_circuitos

    get 'verificar_preinscripcion_escuela/trabajadores/:id',
        to: 'verificar_preinscripcions#wf_verificar_trabajadores',
        as: :verificar_trabajadores
    
    #1.2.1.3 Acciones sobre Verificaciones de Solicitud Adecuacion y construccion
    get 'diferir_preinscripcion_escuela/:id',
        to: 'verificar_preinscripcions#wf_diferir_solicitud',
        as: :diferir_preinscripcion_escuela

    get 'inspeccionar_escuela/:id',
        to: 'verificar_preinscripcions#wf_realizar_inspeccion',
        as: :inspeccionar_preinscripcion_escuela

    get 'estudiar_preinscripcion_escuela/:id',
        to: 'verificar_preinscripcions#wf_realizar_estudio',
        as: :estudiar_preinscripcion_escuela

    get 'cancelar_preinscripcion_escuela/:id',
        to: 'verificar_preinscripcions#wf_cancelar_inspeccion',
        as: :cancelar_preinscripcion_escuela

    get 'solicitud_procesada/:id',
        to: 'verificar_preinscripcions#wf_solitud_procesada',
        as: :verificada

    # post 'rechazar_preinscripcion_escuela/:id',
    #     to: 'verificar_preinscripcions#wf_rechazar_solicitud',
    #     as: :rechazar_preinscripcion_escuela

    # get 'aprobar_preinscripcion_escuela/:id',
    #     to: 'verificar_preinscripcions#wf_aprobar_solicitud',
    #     as: :aprobar_preinscripcion_escuela

  end

  # 1.2.1 Registro
  devise_scope :funcionario do

    get 'funcionarios/new',
        to: 'funcionarios/registrations#new_funcionario'
    get 'funcionarios/show/:id',
        to: 'funcionarios/registrations#show', as: 'funcionarios_show_funcionario'
    post 'funcionarios/create_funcionario',
         to: 'funcionarios/registrations#create_funcionario'
    get 'funcionarios/editf',
        to: 'funcionarios/registrations#edit_funcionario'
    post 'funcionarios/buscar_funcionarios',
         to: 'funcionarios/registrations#buscar_funcionarios'
    get 'funcionarios/editar/:id',
        to: 'funcionarios/registrations#edit_rols_funcionario', as: 'funcionarios_editar_funcionario'
    post 'funcionarios/update_funcionario/:id',
         to: 'funcionarios/registrations#update_funcionario', as: 'funcionarios/update_funcionario'
  end

  devise_for :funcionarios, controllers: { sessions: 'funcionarios/sessions',
                                           registrations: 'funcionarios/registrations'}

  #2. Roles
  resources :rols

  #3. Registro de Interesados
  scope module: 'interesado_cets' do
    resources :interesado_cets, only: [:new, :index, :create, :update, :show]
    post 'interesado_cets/find_interesado_ajax',
         to: 'interesado_cets#find_interesado_ajax'
    resources :tipo_escuelas
  end

  #4. Dynamic Selects
  namespace :dynamic_select do
    get ':estado_id/ciudades', to: 'ciudades#index', as: 'ciudades'
    get ':estado_id/municipios', to: 'municipios#index', as: 'municipios'
    get ':municipio_id/parroquias', to: 'parroquias#index', as: 'parroquias'
    post 'ciudad_municipio', to: 'ciudades#ciudad_municipio'
  end

  #5. Nested Resources Acceder a operadoras de un Representante legal
  resources :representante_legal do
    resources :escuela_transportes, controller: 'escuela_transportes/escuela_transportes'
  end

  resources :jquery_file_uploads, only: [:create, :destroy, :index] do
    member do
      delete 'destroy_no_paginado'
    end
  end

  #6. Preinscripcion de Escuela de Transporte
  namespace :escuela_transportes do

    #6.1 Editar el RIF en caso de que este vencido
    resources :update_rif, only: [:edit, :update]

    #6.2 Documentos del Registro Inicial
    get 'cargar_documentos_registro/:id', to:'documentos_registros#new',as: :cargar_documentos_registro
    post 'documentos_registro/:id', to:'documentos_registros#create',as: :documentos_registro

    #6.3 WIZARD
    #6.3.1 Informacion General e Inicio
    resources :informacion_general, only: [:index, :create, :update, :edit]
    post 'informacion_general/new', to: 'informacion_general#new', as: 'informacion_general_new'
    get 'informacion_general/new', to: 'informacion_general#new_get', as: 'informacion_general_new_get'

    #6.3.2 Documentos Planos de Infraestructura
    get  'cargar_planos_infraestructura/:id', to:'planos_infraestructura#new',
         as: :cargar_planos
    post 'guardar_planos_infraestructura/:id', to:'planos_infraestructura#create',
         as: :guardar_planos

    #6.3.3 Seguro RCV
    resources :seguros, only: [:new, :create]
    patch '/seguros/', to: 'seguros#create'
    post '/rif/', to: 'seguros#rif_aseguradora', as: :rif_a

    #6.3.4 Documentos de Vehiculos
    resources :vehiculos
    post 'vehiculos/buscar_vehiculo_pre', to: 'vehiculos#buscar_vehiculo_pre'
    delete '/eliminar_circuito/:id',
           to: 'circuitos_manejo#eliminar_circuito',
           as: :eliminar_circuito

    #6.3.5 Circuitos de manejo
    get  'listar_circuitos_manejo/:id', to: 'circuitos_manejo#index_circuitos',
         as: :index_circuitos
    get  'ver_circuito_manejo/:id', to: 'circuitos_manejo#show',
         as: :ver_circuito
    get  'crear_circuito_manejo/:id', to:'circuitos_manejo#new',
         as: :crear_circuito
    get  'aditar_circuito_manejo/:id', to:'circuitos_manejo#editar_circuito',
         as: :editar_circuito
    get 'guardar_documentos_circuito_manejo/:id', to:'circuitos_manejo#guardar_documentos_circuito',
        as: :guardar_documentos_circuito
    post 'guardar_circuito_manejo/:id', to:'circuitos_manejo#guardar_circuito',
         as: :guardar_circuito
    patch 'actualizar_circuito_manejo/:id', to:'circuitos_manejo#actualizar_circuito',
          as: :actualizar_circuito

    #6.3.6 Trabajadores
    get 'listar_personal/:id',to: 'personals#index', as: :listar_personals ,constraints: {id: /\d+/}
    get 'find/:id', to:'personals#find',as: :encontrar_personal
    get 'instructor_documents/', to: 'personals#instructor_documents'
    get 'editar_trabajador/:id', to: 'personals#edit', as: :editar_personal
    get 'ver_trabajador/:id', to: 'personals#show', as: :ver_personal
    patch 'update/:id', to: 'personals#update', as: :actualizar_personal
    post 'found/:id', to: 'personals#found', as: :encontro_personal
    post 'save/:id', to: 'personals#save', as: :guardar_personal
    delete 'remove/:id', to: 'personals#remove', as: :eliminar_personal


    #6.3.7 Planilla de Solicitud
    get 'solicitud/preparar/:id',to:'solicitud_adecuacion_acciones#preparar_solicitud', as: :preparar_solicitud_adecuacion
    get 'solicitud/modificar/:id',to:'solicitud_adecuacion_acciones#modificar_solicitud', as: :modificar_solicitud_adecuacion
    get 'solicitud/print', to: 'solicitud_adecuacion_acciones#print', as: :print_solicitud_adecuacion
    get 'solicitud/ver', to: 'solicitud_adecuacion_acciones#ver', as: :ver_solicitud_adecuacion

  end
end

# == Route Map
#
#                                            Prefix Verb   URI Pattern                                                                         Controller#Action
#               escuela_transportes_personals_index GET    /escuela_transportes/personals/index(.:format)                                      escuela_transportes/personals#index
#                escuela_transportes_personals_edit GET    /escuela_transportes/personals/edit(.:format)                                       escuela_transportes/personals#edit
#                escuela_transportes_personals_find GET    /escuela_transportes/personals/find(.:format)                                       escuela_transportes/personals#find
#               escuela_transportes_personals_found GET    /escuela_transportes/personals/found(.:format)                                      escuela_transportes/personals#found

app/views/shared/_document_info.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %i.fa.fa-info-circle
        Nota
      .panel-body{style: "margin-left: 10px"}
        %p
          \- Los datos con
          %span.fa.fa-asterisk.red
          son obligatorios.
          %br
          \- Los datos con
          %span.fa.fa-asterisk.verde
          indican que se debe ingresar al menos uno de esos datos
          %br
          \- El tamaño de cada Documento no puede exceder a 2 MB.
          %br
          \- Los formatos permitidos para los documentos son .jpg .pdf .png .gif
          %br
          \- Si el documento es paginado cada página debe tener nombres diferentes

app/views/shared/_documento_for_group.html.erb
<%if index_group %4 == 0%>
    <div class="row">
    <div class="col-sm-12">
<%end %>


    <div class="col-sm-3">
      <div class="thumbnail popUp">
        <div class="file">
          <% if documento.pdf? %>
              <a data-document="<%= documento.doc.url %>" data-target="#showPdfModal" data-toggle="modal">
                <div class="icon">
                  <i class="fa fa-file"></i>
                </div>
              </a>
          <% else %>
              <%= link_to image_tag(documento.doc.url, size: '100x100'), documento.doc.url, rel: 'lightbox', "data-lightbox" =>documento_requisito.nombre %>
          <% end %>
        </div>
        <h6>
          <strong>Nombre:</strong>
          <%= documento.nombre_documento %>
        </h6>
      </div>
    </div>


<%if index_group == histogram[index_histogram]-1%>
    </div>
    </div>
<%end %>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger.alert-dismissable.alerts-fix
      %h3 No se puede guardar #{model}:
      %p
        - object.errors.each do |name, message|
          &nbsp;
          &nbsp;
          \- &nbsp;
          = message
          %br
%br

app/views/shared/_file_upload_generic.html.haml
%div{id: "#{f.object.documentos_requisitos_por_vista.documento_requisito.nombre}_field_form"}
  .fileinput.fileinput-new.input-group{"data-provides" => "fileinput"}
    .form-control{"data-trigger" => "fileinput"}
      %i.fa.fa-upload.fileinput-exists.pull-left
      -if name_file.present?
        %i.fa.fa-upload.fileinput-new.pull-left{id: "icon_change_#{f.object.id}"}
      %span.fileinput-filename{id: "file_name_change_#{f.object.id}"}
        = name_file.present? ? name_file.to_s.split('/').last : ""
    %span.input-group-addon.btn.btn-default.btn-file

      - if name_file.present?
        %span.fileinput-exists Cambiar
        %span.fileinput-new{id: "button_change_#{f.object.id}"} Cambiar
      - else
        %span.fileinput-new Subir Documento
        %span.fileinput-exists Cambiar
      = f.file_field field,id: "#{f.object.documentos_requisitos_por_vista.documento_requisito.nombre}_file_field"
    -if name_file.present?
      = link_to '',destroy_no_paginado_jquery_file_upload_path(f.object), remote: true,
        method: :delete,
        data:{confirm: 'Seguro de borrar documento?'},
        class:'fa fa-times input-group-addon btn btn-default fileinput-new',
        id: "button_remove_#{f.object.id}",
        :style => "float: none"
    %a.fa.fa-times.input-group-addon.btn.btn-default.fileinput-exists{"data-dismiss" => "fileinput", :href => "#", :style => "float: none"}

  -help||=false
  -unless help.blank?
    %span.help-block
      = help.html_safe

app/views/shared/_jquery_file_upload.html.haml
.row
  .col-md-12
    .ibox.float-e-margins
      .ibox-title
        %h3
          = documento_requisito.descripcion
          -if documento_requisito.obligatorio
            %span.fa.fa-asterisk.red
          %small
            \ -
            Por páginas o documento completo.
      .ibox-content
        .row.form-horizontal
          .col-sm-10.col-sm-offset-2
            = form_for Documento.new,
                       url: jquery_file_uploads_path(modelo_id: modelo.id,
                                                     modelo_type: modelo.class,
                                                     documentos_requisitos_por_vista_id: DocumentosRequisitosPorVista.find_by_tupla(vista,documento_requisito.nombre).id),
                                                     html: {multipart: true, id:'fileupload_'+documento_requisito.nombre,class: 'fileupload-generic', enctype:"multipart/form-data"} do |f|
              .row
                .span16.fileupload-buttonbar
                  .progressbar.fileupload-progressbar.nofade
                    %div{:style => "width:0%;"}
                  %span.btn.btn-success.fileinput-button
                    %span
                      Añadir Página
                      %span.fa.fa-file-o
                    = f.file_field :file, multiple: true
                  %button.btn.btn-primary.start{:type => "submit"}
                    Iniciar Carga
                    %span.fa.fa-upload
                  %button.btn.btn-warning.cancel{:type => "reset"}
                    Cancelar Carga
                    %span.fa.fa-times
                  %button.btn.btn-danger.delete{:type => "button"}
                    Borrar Selección
                    %span.fa.fa-trash
                  %input.toggle{:type => "checkbox"}/
                  %br/
                  .row
                    .span16
                      %table.table.table-striped.zebra-striped
                        %tbody.files
                      #loading
              = render 'shared/jquery_scripts'

app/views/shared/_jquery_scripts.html.erb
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}

    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Procesando...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="fa fa-upload"></i>
                    <span>Subir</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="fa fa-times"></i>
                    <span>Cancelar</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}

    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnail_url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnail_url%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.delete_url) { %}
                <button class="btn btn-danger delete" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="fa fa-trash"></i>
                    <span>Borrar</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="fa fa-times"></i>
                    <span>Cancelar</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>

app/views/shared/_previsualizar_documento.haml
.col-sm-3
  .thumbnail.popUp
    .file
      -if documento.pdf?
        %a{'data-toggle'=>"modal" ,'data-target'=>"#showPdfModal",
           'data-document' => documento.doc.url}
          .icon
            %i{class:'fa fa-file'}
      -else
        = link_to image_tag(documento.doc.url, size: '200x150'), documento.doc.url, rel: 'lightbox', "data-title" => documento.documentos_requisitos_por_vista.documento_requisito.descripcion
    .caption
      %h3
        =documento.documentos_requisitos_por_vista.documento_requisito.nombre.humanize
      %h6
        %strong Nombre:
        =documento.nombre_documento
      %h6
        %strong Obligatorio:
        =documento.documentos_requisitos_por_vista.documento_requisito.obligatorio ? 'Si':'No'
    .po-content.hidden
      .po-title
        %strong Descripcion:
      .po-body
        %p.text-justify
          %strong
            =documento.documentos_requisitos_por_vista.documento_requisito.descripcion.gsub(/:\z/,'')

app/views/shared/_previsualizar_paginas.html.erb
<% if new_group and index ==0 %>
    <div class="row">
      <div class="col-md-12 col-md-offset-0">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h3>
              <%= documento_requisito.descripcion %>
              <small>
                \- Obligatorio:
                <%= documento_requisito.obligatorio ? 'Si':'No' %>
              </small>
            </h3>
          </div>
              <div class="ibox-content">
<% elsif new_group%>

              </div>
              </div>
              </div>
              </div>
              <div class="row">
                <div class="col-md-12 col-md-offset-0">
                  <div class="ibox float-e-margins">
                    <div class="ibox-title">
                      <h3>
                        <%= documento_requisito.descripcion %>
                        <small>
                          \- Obligatorio:
                          <%= documento_requisito.obligatorio ? 'Si':'No' %>
                        </small>
                      </h3>
                    </div>
                     <div class="ibox-content">
<% end %>
<%= render 'shared/documento_for_group',index_histogram:index_histogram, histogram:histogram, documento: documento, documento_requisito: documento_requisito,
           index_group: index_group , close: (not (index==0))%>
<% if index == len-1 %>
    </div>
    </div>
    </div>
    </div>
<% end  %>

app/views/shared/_scripts_jquery_file_upload.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.ui.widget.js' %>
<!-- The Templates and Load Image plugins are included for the FileUpload user interface -->
<script src="https://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
<script src="https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
<script src="https://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
<script src="https://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="https://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.iframe-transport.js' %>
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.fileupload.js' %>
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.fileupload-process.js' %>

<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.fileupload-image.js' %>
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.fileupload-audio.js' %>
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.fileupload-video.js' %>
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.fileupload-validate.js' %>
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/jquery.fileupload-ui.js' %>
<%= javascript_include_tag '/js/plugins/jqueryFileUpload/main.js' %>

app/views/shared/_servicio_intt_documentos.html.haml
-lista_no_paginado = model.documentos_vista(nombre_vista_param)
-if not lista_no_paginado.empty?
  .row
    .col-md-12.col-md-offset-0
      .ibox.float-e-margins
        .ibox-title
          %h3
            Documentos
            %small
              (No Páginados)
        .ibox-content
          .row
            .col-md-12
              - lista_no_paginado.each_with_index  do |documento,index|
                - if (index) % 4 == 0
                  .row.col-sm-12
                = render 'shared/previsualizar_documento', documento: documento

- new_group = nil
- index_group = nil
- name_group_documento_requisito = nil
- list = model.documentos_paginados(nombre_vista_param)
- histogram      = list.group_by{ |v| v.documentos_requisitos_por_vista_id }.map{ |k, v| v.size }
- index_histogram= 0
- list.each_with_index do |documento,index|

  - documento_requisito =  documento.documentos_requisitos_por_vista.documento_requisito
  -if index == 0
    - new_group = true
    - name_group_documento_requisito = documento_requisito.nombre
    - index_group = 0

  - if index > 0 and not name_group_documento_requisito == documento_requisito.nombre
    - new_group = true
    - index_group = 0
    - index_histogram+=1
    - name_group_documento_requisito = documento_requisito.nombre

  = render 'shared/previsualizar_paginas',histogram:histogram,index_histogram:index_histogram,index:index, len: list.length, documento: documento, documento_requisito: documento_requisito, new_group: new_group,index_group:index_group
  -new_group   = false
  -index_group += 1

=render 'shared/show_modal_pdf'

app/views/shared/_show_modelo_documento_paginado.html.haml
-Vista.find_documentos_requisitos(vista).each do |documento_requisito|
  = render 'shared/jquery_file_upload', modelo: modelo, vista: vista, documento_requisito: documento_requisito

app/views/shared/_show_modelo_documentos_no_paginados.html.haml
-#partial para documentos NO paginados
-indice_documento||= 0
= model.fields_for :documentos, list_documents,child_index: indice_documento  do |documento|
  %div{id: ""}
    = documento.hidden_field :documentos_requisitos_por_vista_id, value: documento.object.documentos_requisitos_por_vista_id
    .form-group.doc-feedback
      .group
        = documento.label documento.object.documentos_requisitos_por_vista.documento_requisito.nombre.to_sym,
                   class: 'col-sm-3 control-label' do
          = documento.object.documentos_requisitos_por_vista.documento_requisito.descripcion
          - if documento.object.documentos_requisitos_por_vista.documento_requisito.obligatorio
            %span.fa.fa-asterisk.red
          - elsif documento.object.documentos_requisitos_por_vista.documento_requisito.almenos_uno
            %span{class: "fa fa-asterisk #{documento.object.documentos_requisitos_por_vista.grupo_documentos_uno.icon_color}"}
        .col-sm-9
          = render 'shared/file_upload_generic',f: documento,
                      field: :doc,
                      name_file: documento.object.doc

  -documento.options[:child_index] += 1

app/views/shared/_show_modelo_modals_documentos_paginados.html.haml
-Vista.find_documentos_requisitos(vista).each do |documento_requisito|
  .row
    .col-md-12
      .ibox.float-e-margins
        .ibox-title
          %h3
            =documento_requisito.descripcion
            - if documento_requisito.obligatorio
              %span.fa.fa-asterisk.red
            %small
              \ -
              Por páginas o documento completo.
        .ibox-content
          .row
            .col-sm-3
              %button.btn.btn-success.btn-block{"data-toggle"=>"modal","data-target"=>"##{documento_requisito.nombre.camelize}"}
                Subir Documento

  %div.modal.fade{id:documento_requisito.nombre.camelize,"aria-hidden" => "true", "aria-labelledby" => "poderNotariadoModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog.modal-lg
      .modal-content
        .modal-header.blue-bg
          %button.close{"data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
          %h4.modal-title
            =documento_requisito.descripcion
        .modal-body
          = render 'shared/jquery_file_upload', modelo: modelo, vista: vista, documento_requisito: documento_requisito
        .modal-footer
          Al cargar el documento completo:
          %a.btn{"data-dismiss" => "modal"}
            Cerrar Ventana
            %span{"aria-hidden" => "true"} &times;

app/views/shared/_solicitud_documents.html.haml
= f.fields_for :solicituds, @solicitud do |solicitud|
  =render 'shared/show_modelo_documentos_no_paginados', model: solicitud, list_documents: list_documents