config/routes.rb
                                           registrations: 'funcionarios/registrations'}

  #2. Roles
  resources :rols

  #3. Registro de Interesados
  scope module: 'interesado_cets' do
    resources :interesado_cets, only: [:new, :index, :create, :update, :show]
    post 'interesado_cets/find_interesado_ajax',
         to: 'interesado_cets#find_interesado_ajax'
    resources :tipo_escuelas
  end

  #4. Dynamic Selects
  namespace :dynamic_select do
    get ':estado_id/ciudades', to: 'ciudades#index', as: 'ciudades'
    get ':estado_id/municipios', to: 'municipios#index', as: 'municipios'
    get ':municipio_id/parroquias', to: 'parroquias#index', as: 'parroquias'
    post 'ciudad_municipio', to: 'ciudades#ciudad_municipio'
  end

  #5. Nested Resources Acceder a operadoras de un Representante legal
  resources :representante_legal do
    resources :escuela_transportes, controller: 'escuela_transportes/escuela_transportes'
  end

  resources :jquery_file_uploads, only: [:create, :destroy, :index] do
    member do
      delete 'destroy_no_paginado'
    end
  end

  #6. Preinscripcion de Escuela de Transporte
  namespace :escuela_transportes do

    #6.1 Editar el RIF en caso de que este vencido
    resources :update_rif, only: [:edit, :update]

    #6.2 Documentos del Registro Inicial
    get 'cargar_documentos_registro/:id', to:'documentos_registros#new',as: :cargar_documentos_registro
    post 'documentos_registro/:id', to:'documentos_registros#create',as: :documentos_registro

    #6.3 WIZARD
    #6.3.1 Informacion General e Inicio
    resources :informacion_general, only: [:index, :create, :update, :edit]
    post 'informacion_general/new', to: 'informacion_general#new', as: 'informacion_general_new'
    get 'informacion_general/new', to: 'informacion_general#new_get', as: 'informacion_general_new_get'

    #6.3.2 Documentos Planos de Infraestructura
    get  'cargar_planos_infraestructura/:id', to:'planos_infraestructura#new',
         as: :cargar_planos
    post 'guardar_planos_infraestructura/:id', to:'planos_infraestructura#create',
         as: :guardar_planos

    #6.3.3 Seguro RCV
    resources :seguros, only: [:new, :create]
    patch '/seguros/', to: 'seguros#create'
    post '/rif/', to: 'seguros#rif_aseguradora', as: :rif_a

    #6.3.4 Documentos de Vehiculos
    resources :vehiculos
    post 'vehiculos/buscar_vehiculo_pre', to: 'vehiculos#buscar_vehiculo_pre'
    delete '/eliminar_circuito/:id',
           to: 'circuitos_manejo#eliminar_circuito',
           as: :eliminar_circuito

    #6.3.5 Circuitos de manejo
    get  'listar_circuitos_manejo/:id', to: 'circuitos_manejo#index_circuitos',
         as: :index_circuitos
    get  'ver_circuito_manejo/:id', to: 'circuitos_manejo#show',
         as: :ver_circuito
    get  'crear_circuito_manejo/:id', to:'circuitos_manejo#new',
         as: :crear_circuito
    get  'aditar_circuito_manejo/:id', to:'circuitos_manejo#editar_circuito',
         as: :editar_circuito
    get 'guardar_documentos_circuito_manejo/:id', to:'circuitos_manejo#guardar_documentos_circuito',
        as: :guardar_documentos_circuito
    post 'guardar_circuito_manejo/:id', to:'circuitos_manejo#guardar_circuito',
         as: :guardar_circuito
    patch 'actualizar_circuito_manejo/:id', to:'circuitos_manejo#actualizar_circuito',
          as: :actualizar_circuito

    #6.3.6 Trabajadores
    get 'listar_personal/:id',to: 'personals#index', as: :listar_personals ,constraints: {id: /\d+/}
    get 'find/:id', to:'personals#find',as: :encontrar_personal
    get 'instructor_documents/', to: 'personals#instructor_documents'
    get 'editar_trabajador/:id', to: 'personals#edit', as: :editar_personal
    get 'ver_trabajador/:id', to: 'personals#show', as: :ver_personal
    patch 'update/:id', to: 'personals#update', as: :actualizar_personal
    post 'found/:id', to: 'personals#found', as: :encontro_personal
    post 'save/:id', to: 'personals#save', as: :guardar_personal
    delete 'remove/:id', to: 'personals#remove', as: :eliminar_personal


    #6.3.7 Planilla de Solicitud
    get 'solicitud/preparar/:id',to:'solicitud_adecuacion_acciones#preparar_solicitud', as: :preparar_solicitud_adecuacion
    get 'solicitud/modificar/:id',to:'solicitud_adecuacion_acciones#modificar_solicitud', as: :modificar_solicitud_adecuacion
    get 'solicitud/print', to: 'solicitud_adecuacion_acciones#print', as: :print_solicitud_adecuacion
    get 'solicitud/ver', to: 'solicitud_adecuacion_acciones#ver', as: :ver_solicitud_adecuacion

  end
end

# == Route Map
#
#                                            Prefix Verb   URI Pattern                                                                         Controller#Action
#               escuela_transportes_personals_index GET    /escuela_transportes/personals/index(.:format)                                      escuela_transportes/personals#index
#                escuela_transportes_personals_edit GET    /escuela_transportes/personals/edit(.:format)                                       escuela_transportes/personals#edit
#                escuela_transportes_personals_find GET    /escuela_transportes/personals/find(.:format)                                       escuela_transportes/personals#find
#               escuela_transportes_personals_found GET    /escuela_transportes/personals/found(.:format)                                      escuela_transportes/personals#found
#                escuela_transportes_personals_save GET    /escuela_transportes/personals/save(.:format)                                       escuela_transportes/personals#save
#              escuela_transportes_personals_update GET    /escuela_transportes/personals/update(.:format)                                     escuela_transportes/personals#update
#              escuela_transportes_personals_remove GET    /escuela_transportes/personals/remove(.:format)                                     escuela_transportes/personals#remove
#                                              root GET    /                                                                                   static_pages#home
#                                    iniciar_sesion GET    /iniciar_sesion(.:format)                                                           devise/sessions#new
#                                          registro GET    /registro(.:format)                                                                 session_users/registrations#nuevo_registro
#                    cambio_contrasena_session_user GET    /cambio_contrasena_u(.:format)                                                      session_users/sessions#edit_password
#                              recuperar_contrasena GET    /recuperar_contrasena(.:format)                                                     session_users/passwords#new
#                             actualizar_contrasena PATCH  /actualizar_contrasena(.:format)                                                    session_users/sessions#update_password
#                             reestablecer_password POST   /reestablecer_password(.:format)                                                    session_users/passwords#permit_reset_password
#                                     cerrar_sesion DELETE /cerrar_sesion(.:format)                                                            devise/sessions#destroy
#                             session_user_password POST   /session_users/password(.:format)                                                   session_users/passwords#create
#                         new_session_user_password GET    /session_users/password/new(.:format)                                               session_users/passwords#new
#                        edit_session_user_password GET    /session_users/password/edit(.:format)                                              session_users/passwords#edit
#                                                   PATCH  /session_users/password(.:format)                                                   session_users/passwords#update
#                                                   PUT    /session_users/password(.:format)                                                   session_users/passwords#update
#                  cancel_session_user_registration GET    /session_users/cancel(.:format)                                                     session_users/registrations#cancel
#                         session_user_registration POST   /session_users(.:format)                                                            session_users/registrations#create
#                     new_session_user_registration GET    /session_users/sign_up(.:format)                                                    session_users/registrations#new
#                    edit_session_user_registration GET    /session_users/edit(.:format)                                                       session_users/registrations#edit
#                                                   PATCH  /session_users(.:format)                                                            session_users/registrations#update
#                                                   PUT    /session_users(.:format)                                                            session_users/registrations#update
#                                                   DELETE /session_users(.:format)                                                            session_users/registrations#destroy
#                         session_user_confirmation POST   /session_users/confirmation(.:format)                                               devise/confirmations#create
#                     new_session_user_confirmation GET    /session_users/confirmation/new(.:format)                                           devise/confirmations#new
#                                                   GET    /session_users/confirmation(.:format)                                               devise/confirmations#show

app/controllers/escuela_transportes/circuitos_manejo_controller.rb
class EscuelaTransportes::CircuitosManejoController < ApplicationController
  include SolicitudConstruccionEscuelaHelper

  before_filter :autenticar_session_user!
  before_action :autorized_user
  before_action :set_escuela_transporte_preinscripcion,only:[:index_circuitos, :new, :editar_circuito]
  before_action :cargar_representante
  before_action :cargar_rif
  before_action :cargar_solicitud_escuela, only: [:actualizar_circuito,:guardar_circuito,:show]

  helper_method :nombre_solicitud
  helper_method :nombre_vista
  helper_method :reload_documents?

  def index_circuitos
    init_solicitud(nombre_solicitud,@escuela_transporte)
    only_initial_solicitud
    # centinel =  @solicitud.circuitos.empty? ? true : false

    # @solicitud.circuitos.each_with_index  do  |circuito,index|
    #   if not circuito.documentos_registro_circuito_completos?
    #     centinel =true
    #     break
    #   end
    # end
    #
    # if centinel
    #   @solicitud.update_index_mask(4,false)
    # else
    #   @solicitud.update_index_mask(4)
    # end
  end

  def new
    init_solicitud(nombre_solicitud,@escuela_transporte)
    only_initial_solicitud
    @circuito = @solicitud.circuitos.build
  end

  def show
    @circuito = @solicitud.circuitos.find_by(id: params[:circuito_id])
    only_initial_solicitud
    check_circuito
  end

  def editar_circuito
    init_solicitud(nombre_solicitud,@escuela_transporte)
    only_initial_solicitud
    @circuito = @solicitud.circuitos.find_by(id: params[:circuito_id])
    check_circuito
  end

  def guardar_circuito
    respond_to do |format|
      only_initial_solicitud
      @guardo = @solicitud.update(params_solicitud_circuito)
      # @solicitud.update_index_mask(4,false) if @guardo
      flash[:success]='Circuito de manejo Guardado exitosamente, a continuacion suba los siguientes documentos' if @guardo
      @circuito =  @solicitud.circuitos.last
      format.js
    end
  end

  def guardar_documentos_circuito
    @circuito =  Circuito.includes(:solicitud).find_by(id: params[:id])
    check_circuito
    @escuela_transporte= @representante_legal.escuela_transportes.joins(solicituds: :circuitos).where(circuitos: {id: @circuito.id} ).last
    only_initial_solicitud
    if @escuela_transporte.nil?
      redirect_to root_path
      return
    end

    if @circuito.documentos_registro_circuito_completos?
      # @circuito.solicitud.update_index_mask(4)
      flash[:success]= 'Documentos de Circuito Guardados Satisfactoriamente'
      redirect_to escuela_transportes_index_circuitos_path(id: @escuela_transporte.id)
      return
    else
      # @circuito.solicitud.update_index_mask(4,false)
      flash[:danger]= 'Debe cargar los Documentos Paginados, intente denuevo '
      redirect_to escuela_transportes_editar_circuito_path(id:@escuela_transporte, circuito_id: @circuito)
    end
  end

  def actualizar_circuito
    only_initial_solicitud
    @circuito =  @solicitud.circuitos.find_by(id:params[:solicitud][:circuitos_attributes]['0'][:id])
    check_circuito
    if @solicitud.update(params_solicitud_circuito)
      if @circuito.documentos_registro_circuito_completos?
        # @solicitud.update_index_mask(4)
        flash[:success]='Circuito de manejo Guardado exitosamente'
        redirect_to escuela_transportes_index_circuitos_path(id: @escuela_transporte.id)
      else
        # @solicitud.update_index_mask(4,false)
        flash[:danger]= 'Debe cargar los Documentos Paginados, intente denuevo '
        redirect_to escuela_transportes_editar_circuito_path(id:@escuela_transporte, circuito_id: @circuito)
      end
    else
      render'escuela_transportes/circuitos_manejo/editar_circuito', url: escuela_transportes_actualizar_circuito_path, method: :patch
    end
  end


  def eliminar_circuito
    circuito= Circuito.includes(:solicitud).find_by(id: params[:id])
    if circuito.present?

      @escuela_transporte= @representante_legal.escuela_transportes.joins(:solicituds).where(solicituds:{id: circuito.solicitud.id}).last
      only_initial_solicitud
      if  @escuela_transporte.nil?
        flash[:danger] = 'Este circuito no existe para ninguna de sus Escuelas'
        redirect_to root_path
      else
        circuito.destroy
        flash[:success] = 'Circuito de Manejo Eliminado con exito'

        # solicitud = Solicitud.includes(:circuitos).find_by(id: circuito.solicitud.id)
        # if solicitud.circuitos.empty?
        #   solicitud.update_index_mask(4,false)
        # end

        redirect_to escuela_transportes_index_circuitos_path(id: @escuela_transporte.id)
      end
    else
      flash[:danger] = 'Este circuito no existe'
      redirect_to root_path
    end
  end

  def nombre_solicitud
    :preinscripcion
  end

  def nombre_vista
    :registro_circuitos_manejo
  end

  def reload_documents?
    not (action_name == 'new' or action_name == 'editar_circuito')
  end

  private

  def check_circuito
    if @circuito.nil?
      flash[:danger]='Circuito No existente'
      redirect_to root_path
    end
  end
  def cargar_solicitud_escuela
    @solicitud = Solicitud.includes(:servicio_intt).find_by(id: params[:id])
    if @solicitud.nil? or (not @solicitud.servicio_intt_type == 'EscuelaTransporte')
      flash[:danger]='Solicitud no Existente'
      redirect_to root_path
    else
      only_initial_solicitud
      @escuela_transporte = @representante_legal.escuela_transportes.find_by(id:@solicitud.servicio_intt.id)
      if @escuela_transporte.nil?
        flash[:danger]='Solicitud no le pertenece a ninguna de sus Escuelas'
        redirect_to root_path
      end
    end
  end

  def cargar_rif
    #TODO Arreglar el RIF de representante legal, o este rif
    @rif = @representante_legal.rif[0]
    @rif +='-'
    @rif += @representante_legal.rif[1..@representante_legal.rif.length-2]
    @rif +='-'
    @rif +=@representante_legal.rif[@representante_legal.rif.length-1]
  end

  def cargar_representante
    @representante_legal =  current_session_user.representante_legal
  end

  def params_solicitud_circuito
    params.require(:solicitud).permit(:id,circuitos_attributes: [:id,:tipo_circuito,:descripcion_ruta,
                                                                 documentos_attributes:
                                                                     [:id, :documentos_requisitos_por_vista_id,:doc]
                                         ])
  end

  def params_circuito_documento
    params.require(:circuito).permit(:id,documentos_attributes: [:id, :documentos_requisitos_por_vista_id,:doc])
  end
end

app/helpers/escuela_transportes_helper.rb
module EscuelaTransportesHelper
end

app/views/escuela_transportes/personals/_form_personal.html.haml
.row
  .col-md-12
    .ibox.float-e-margins
      .ibox-content
        .row.form-horizontal
          = form_for @personal, url: url,
            html: {method: method, multipart: true,id:'form_trabajador_registro'}, remote: remote do |personal|
            = render 'shared/error_messages', object: personal.object, model: 'Trabajador'
            .row.col-sm-12
              .form-group.col-sm-4
                =personal.label :nombre,'Nombre:' , class: 'col-sm-4 control-label'
                .col-sm-8
                  = personal.text_field :nombre,
                    class:'form-control',
                    disabled: :true
              .form-group.col-sm-4
                =personal.label :apellido ,'Apellido:', class: 'col-sm-4 control-label'
                .col-sm-8
                  = personal.text_field :apellido,
                    class:'form-control',
                    disabled: :true
              .form-group.col-sm-4
                =personal.label :cedula ,'Cédula:', class: 'col-sm-4 control-label'
                .col-sm-3
                  = personal.text_field :nacionalidad,
                    class:'form-control',
                    disabled: :true
                .col-sm-5
                  = personal.text_field :cedula,
                    class:'form-control',
                    disabled: :true
            .row.col-sm-12
              .form-group.col-sm-4
                = personal.label :tipo_personal , class: 'col-sm-4 control-label' do
                  Tipo de circuito:
                  %span.fa.fa-asterisk.red
                .col-sm-8
                  =personal.select :tipo_personal, options_for_select({'Docente' => 'docente',
                              'Instructor'=>'instructor','Obrero'=> 'obrero','Directivo'=> 'directivo',
                              'Administrativo'=> 'administrativo'},
                              :selected=> @personal.tipo_personal.nil? ? 'docente' : @personal.tipo_personal),
                             {id: 'select-documento'}, {class: 'form-control'}
            #document-trabajadores
              =render 'shared/show_modelo_documentos_no_paginados', model: personal, list_documents: load_documentos(:trabajadores, @personal,true)
            #document-trabajadores-intructores
              - if @personal.instructor?
                =render 'shared/show_modelo_documentos_no_paginados',indice_documento:1, model: personal, list_documents: load_documentos(:trabajadores_instructores, @personal,true)
            %br
            %br
            .form-group
              .col-sm-3.col-sm-offset-9
                = personal.button(type: 'submit', class: 'btn btn-success btn-block',id:'button_trabajador_registro',
                 data: { disable_with: 'Guardando ...' }) do
                  Guardar Trabajador
                  %i.fa.fa-save
:javascript
  $("#form_trabajador_registro").bind("submit", function() {
    $(this).find(":input").removeAttr("disabled");
    //$('#button_trabajador_registro').remove();

  });

app/views/escuela_transportes/personals/_instructor_documents_partial.html.haml
= fields_for Personal.new do |personal|
  =render 'shared/show_modelo_documentos_no_paginados', model: personal, indice_documento: 1,list_documents: load_documentos(:trabajadores_instructores, personal.object,true)

app/views/escuela_transportes/personals/edit.html.haml
= provide(:title, 'Edición de Trabajador de Escuela de transporte')

= render 'escuela_transportes/shared/ficha_datos'

.wrapper.wrapper-content
  .row.animated.fadeInRight
    .col-md-12
      .ibox.float-e-margins
        .ibox-content
          %h2
            Registro de Trabajadores
          %ol.breadcrumb
            %li
              = link_to 'Información General', escuela_transportes_informacion_general_new_get_path(id: @escuela_transporte)
            %li
              = link_to 'Planos Infraestructura',escuela_transportes_cargar_planos_path(id: @escuela_transporte)
            -if @solicitud.seguro_nil_or_por_flota?
              %li
                = link_to 'Datos del Seguro RCV', new_escuela_transportes_seguro_path(id: @escuela_transporte)
            %li
              = link_to 'Documentos de Vehiculos', escuela_transportes_vehiculos_path(id: @escuela_transporte.id)
            %li
              = link_to 'Registro de Circuitos de Manejo', escuela_transportes_index_circuitos_path(id: @escuela_transporte.id)
            %li
              = link_to 'Registro de trabajadores', escuela_transportes_listar_personals_path(id: @escuela_transporte.id)

  .row.col-md-12#flash-error-busqueda-personal
.row.animated.fadeInRight
  .col-md-12
    .ibox.float-e-margins
      .ibox-title
        %h3
          Datos del Trabajador
      .ibox-content
        = render 'escuela_transportes/personals/form_personal', remote: false, method: :patch,url:escuela_transportes_actualizar_personal_path(id:@escuela_transporte,personal_id:@personal)
.row.animated.fadeInRight
  .col-md-12
    .ibox.float-e-margins
      .ibox-content
        .row
          .col-sm-2
            = link_to  escuela_transportes_listar_personals_path(id: @escuela_transporte.id),class: "btn btn-info" do
              Listar Trabajadores
              %i.fa.fa-users

app/views/escuela_transportes/personals/find.html.haml
= provide(:title, 'Registro de Trabajadores de Escuela Transporte')
.wrapper.wrapper-content
  .row.animated.fadeInRight
    = render 'escuela_transportes/shared/ficha_datos'
    = render 'escuela_transportes/shared/breadcrum_wizard_solicitud_adecuacion',title:'Registro de Trabajador',solicitud: @solicitud, icon: '<i class="fa fa-user"></i>'
.row.col-md-12#flash-error-busqueda-personal
.row.animated.fadeInRight
  .col-md-12
    .ibox.float-e-margins
      .ibox-title
        %h5
          Datos del Trabajador
      .ibox-content
        .row{id: "form-personal-solicitud-#{@solicitud.id}"}
          = form_for :trabajador, url: escuela_transportes_encontro_personal_path(@escuela_transporte), method: :post,
            html: {class: 'form-horizontal m-t-md', id:'search-trabajador-form'},remote: true do |trabajador|
            .form-group
              = trabajador.label :cedula , 'Documento:', class:'control-label col-sm-5 'do
                Documento:
                %span.glyphicon-asterisk.red
              .col-sm-7
                .row
                  .col-sm-3
                    = trabajador.select :nacionalidad,  options_for_select({'E' => 'E','V'=> 'V'}, selected: 'V'),
                     {id: 'select-documento'}, {class: 'form-control '}
                  .col-sm-3
                    = trabajador.text_field :cedula, class: 'form-control',
                     autofocus: true, id: 'documento-trabajador-saime',
                     maxlength: 8
            %br/
            %br/
            .form-inline.col-sm-offset-4
              .form-group
                = trabajador.label :fecha_nacimiento, class:'col-sm-10 'do
                  Fecha Nacimiento:
                  %span.glyphicon-asterisk.red
              .form-group
                = trabajador.date_select :fecha_nacimiento,
                options = { start_year: Date.today.year - 98,
                            end_year: Date.today.year-18,
                            use_two_digit_numbers: true,
                            selected:Date.today.year-18},
                html_options = { class: 'form-control',
                                 format: :default}
            .row.col-sm-12
              .col-sm-3.col-lg-offset-9#div-button-encontrar
                = trabajador.button(type: 'submit', class: 'btn btn-success btn-block',
                           data: { disable_with: 'Buscando Trabajador' }, disabled:true) do
                  Buscar Trabajador
                  %i.fa.fa-search

#document-trabajadores
%div{id: "form-documentos-personal-solicitud-#{@solicitud.id}"}


.row.animated.fadeInRight
  .col-md-12
    .ibox.float-e-margins
      .ibox-content
        .row
          .col-sm-2
            = link_to  escuela_transportes_listar_personals_path(id: @escuela_transporte.id),class: "btn btn-info" do
              Listar Trabajadores
              %i.fa.fa-users

app/views/escuela_transportes/personals/found.js.erb
<% if @error %>
    $('#flash-error-busqueda-personal').html('<%= j render('layouts/flash_message') %>');
    <% flash.discard %>
<% else %>
    $('#flash-error-busqueda-personal').html('');
    <% flash.discard %>
    <% init_solicitud(nombre_solicitud,@escuela_transporte)%>
    $('#div-button-encontrar').html('<%= link_to 'Buscar otro Trabajador' , escuela_transportes_encontrar_personal_path(id:@escuela_transporte)%>');
    $('#documento-trabajador-saime').prop( "disabled", true );
    $('#trabajador_nacionalidad').prop( "disabled", true );
    $("[id^='trabajador_fecha_nacimiento_']").prop( "disabled", true );
    $('#document-trabajadores').html('<%= j render('escuela_transportes/personals/form_personal', remote:true, method: :post,url: escuela_transportes_guardar_personal_path(@escuela_transporte)) %>');
<% end  %>

app/views/escuela_transportes/personals/index.html.haml
= provide(:title, 'Preinscripcion Escuelas de Transporte')
.wrapper.wrapper-content
  .row.animated.fadeInRight
    = render 'escuela_transportes/shared/ficha_datos', show: false
    = render 'escuela_transportes/shared/breadcrum_wizard_solicitud_adecuacion',title:'Registro de Trabajadores',solicitud: @solicitud, icon: '<i class="fa fa-users"></i>'

  .row.animated.fadeInRight
    .col-md-12.col-md-offset-0
      %ul.text-muted.leyenda
        %li.text-justify
          Puede registrar un Trabajador haciendo click en
          %span.verde-button-primary
            Agregar Trabajador
  - if @solicitud.personals.empty?
    .ibox-content.text-center.animated.fadeInRight
      %h3.font-bold No posee Trabajadores para esta Solicitud
      =link_to escuela_transportes_encontrar_personal_path(@escuela_transporte) ,
      class: 'btn btn-primary  pull-center' do
        Agregar Trabajador
        %i.fa.fa-user-plus

  - else
    .row
      .col-md-12.col-md-offset-0
        .ibox.float-e-margins
          .ibox-content
            =link_to escuela_transportes_encontrar_personal_path(@escuela_transporte) ,
              class: 'btn btn-primary  pull-center' do
              Agregar Trabajador
              %i.fa.fa-user-plus
            %table.table.table-striped.table-bordered.table-condensed
              %thead
                %tr
                  %th.text-center Nombre
                  %th.text-center Apellido
                  %th.text-center Cedúla
                  %th.text-center Tipo de Personal
                  %th.text-center Documentos Completos
                  %th.text-center{:colspan => '3'}
                    Acciones

              %tbody
              - @solicitud.personals.order(:tipo_personal).each do |personal|
                %tr
                  %td.text-center= personal.nombre
                  %td.text-center= personal.apellido
                  %td.text-center= personal.cedula
                  %td.text-center= personal.tipo_personal
                  %td.text-center
                    -if personal.documentos_registro_completos?
                      %i.fa.fa-check
                    -else
                      Debe Completar Carga Documentos
                  %td.text-center
                    = link_to  escuela_transportes_ver_personal_path(id:@escuela_transporte,personal_id: personal.id) do
                      %i.fa.fa-search
                    = link_to escuela_transportes_editar_personal_path(id: @escuela_transporte, personal_id: personal.id) do
                      %i.fa.fa-pencil-square-o
                    = link_to  escuela_transportes_eliminar_personal_path(id: personal.id) , method: :delete,
                      data: { confirm:'¿Seguro que desea Borrar Trabajador?' } do
                      %i.fa.fa-trash-o

  %br
  .row
    .col-sm-12
      .ibox.float-e-margins
        .ibox-content
          .row
            .col-sm-2
              = link_to  escuela_transportes_index_circuitos_path(id: @escuela_transporte.id),
              class: "btn btn-info" do
                volver a circuitos
                %i.fa.fa-road
            .col-sm-3.col-lg-offset-7
              = link_to escuela_transportes_preparar_solicitud_adecuacion_path(id: @escuela_transporte) ,
                class: 'btn btn-success btn-block' ,data: { disable_with: 'Enviando ...' } do
                Enviar Solicitud
                %i.fa.fa-paper-plane

app/views/escuela_transportes/personals/remove.html.erb
<h1>EscuelaTransportes::Personals#remove</h1>
<p>Find me in app/views/escuela_transportes/personals/remove.html.erb</p>

app/views/escuela_transportes/personals/save.js.erb
$('#document-trabajadores').html('<%= j render('escuela_transportes/personals/form_personal',remote:true, method: :post,url: escuela_transportes_guardar_personal_path(@escuela_transporte)) %>');

app/views/escuela_transportes/personals/show.html.haml
= provide(:title, 'Visualizar Trabajador')
.wrapper.wrapper-content
  .row.animated.fadeInRight
    = render 'escuela_transportes/shared/ficha_datos'
    = render 'escuela_transportes/shared/breadcrum_wizard_solicitud_adecuacion',title:'Registro de Trabajadores',solicitud: @solicitud

.row.animated.fadeInRight
  = render 'escuela_transportes/shared/ficha_datos', show: false

.row.animated.fadeInRight
  .col-md-12.col-md-offset-0
    .ibox.float-e-margins
      .ibox-title
        %h3
      .ibox-content
        .row
          %table.table.table-striped.table-bordered.table-condensed
            %thead
              %tr
                %th.text-center
                  Nombres
                %th.text-center
                  Apellidos
                %th.text-center
                  Cédula
                %th.text-center
                  Tipo de Personal
              %tbody
                %tr
                  %td.text-center
                    #{@personal.nombre}
                  %td.text-center
                    #{@personal.apellido}
                  %td.text-center
                    ="#{@personal.nacionalidad+'-'+@personal.cedula}"
                  %td.text-center
                    #{@personal.tipo_personal}

= render 'shared/servicio_intt_documentos', model: @personal, nombre_vista_param: :trabajadores
= render 'shared/servicio_intt_documentos', model: @personal,
  nombre_vista_param: :trabajadores_instructores if @personal.instructor?

.row.animated.fadeInRight
  .col-md-12
    .ibox.float-e-margins
      .ibox-content
        .row
          .col-sm-2
            = link_to 'Listar Trabajadores',
            escuela_transportes_listar_personals_path(id: @escuela_transporte.id),
            class: "btn btn-info"
  %br
  %br
  %br